package org.example.bot;

public enum UserState {
    AWAITING_MESSAGE,
    AWAITING_START,
    FOOD_DRINK_SELECTION,
    ORDER_SELECTION,
    OLD_ORDER_FOOD_DRINK_SELECTION,
    CHOICE_POSITION,
    AMOUNT_SELECTION,
    PIZZA_TOPPINGS
}
